# Generated by Django 4.2.20 on 2026-09-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsAvailable',
            fields=[
                ('roomId', models.IntegerField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=100)),
                ('roomCapacity', models.IntegerField()),
                ('roomImages', models.ImageField(upload_to='roomImages')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedDate', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('bookedByUsername', models.ForeignKey(blank=True, db_column='bookedByUsername', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('roomId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomBooking.roomsavailable')),
            ],
        ),
    ]
