# Generated by Django 4.2.20 on 2026-09-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roomId',
            field=models.ForeignKey(blank=True, db_column='roomId', null=True, on_delete=django.db.models.deletion.CASCADE, to='roomBooking.roomsavailable'),
        ),
    ]
