# Generated by Django 4.2.20 on 2026-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0002_alter_booking_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookedRoom',
            field=models.CharField(blank=True, db_column='bookedRoom', max_length=100, null=True),
        ),
    ]
