# Generated by Django 4.2.20 on 2026-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0003_booking_bookedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsavailable',
            name='projector',
            field=models.CharField(blank=True, db_column='projector', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='roomTv',
            field=models.CharField(blank=True, db_column='roomTv', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='whiteBoard',
            field=models.CharField(blank=True, db_column='whiteBoard', max_length=100, null=True),
        ),
    ]
