# Generated by Django 4.2.20 on 2026-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0004_roomsavailable_projector_roomsavailable_roomtv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsavailable',
            name='projector',
        ),
        migrations.RemoveField(
            model_name='roomsavailable',
            name='roomTv',
        ),
        migrations.RemoveField(
            model_name='roomsavailable',
            name='whiteBoard',
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='videoconferencing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomsavailable',
            name='whiteboard',
            field=models.BooleanField(default=False),
        ),
    ]
