# Generated by Django 4.2.20 on 2026-09-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0005_remove_roomsavailable_projector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsavailable',
            old_name='videoconferencing',
            new_name='videoConferencing',
        ),
        migrations.RenameField(
            model_name='roomsavailable',
            old_name='whiteboard',
            new_name='whiteBoard',
        ),
    ]
