# Generated by Django 4.2.20 on 2026-09-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsavailable',
            old_name='monitor',
            new_name='roomMonitor',
        ),
    ]
