# Generated by Django 4.2.20 on 2026-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBooking', '0008_rename_monitor_roomsavailable_roommonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsavailable',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text='Check this box to disable room bookings and mark as maintenance', verbose_name='Under Maintenance'),
        ),
    ]
